[0707/133303:INFO:main.cpp(37)] test log
[0707/133303:INFO:main.cpp(24)] in func 3
[0707/133303:INFO:main.cpp(18)] func 2
[0707/133303:FATAL:main.cpp(19)] Check failed: 2==3. 
Backtrace:
	StackTrace::StackTrace() [0xa4e3d6]
	logging::LogMessage::~LogMessage() [0xa4c31c]
	func2() [0x80488c3]
	func3() [0x8048995]
	main [0x80489f7]
	0x1c7de6
	0x8048779

